// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cgycppqcvpxfthpnaewn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNneWNwcHFjdnB4ZnRocG5hZXduIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyOTg4MTEsImV4cCI6MjA3Mzg3NDgxMX0.mTx4c-_3kVCsBjgTyic1ySYJbe4mdDbznsgXK_gFXgY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});